version: "3.9"

services:
  ai-backend:
    build:
      context: ./ai-backend
      dockerfile: Dockerfile
    container_name: ai-backend
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX: ${PINECONE_INDEX}
    ports:
      - "8080:8080"

  ai-frontend:
    build:
      context: ./ai-frontend
      dockerfile: Dockerfile
    container_name: ai-frontend
    ports:
      - "3000:3000"
    depends_on:
      - ai-backend
